version: 1.0.{build}
image: Ubuntu

install:
  - npm install

before_build:
  - git fetch --all
  - git reset --hard origin/main

build_script:
  - npm run build

artifacts:
  - path: dist

deploy:
  - provider: GitHubPages
    auth_token: $(GITHUB_TOKEN)
    repo: simplespacej/whack-a-mole
    branch: gh-pages
    folder: dist
    on:
      branch: main
