version: 1.0.{build}
image: Ubuntu

install:
  - npm install

before_build:
  - git fetch --all
  - git checkout main
  - git pull origin main
  - git fetch origin gh-pages || echo "No gh-pages branch yet"

build_script:
  - npm run build

artifacts:
  - path: dist

after_build:
  - echo "Deploying to GitHub Pages..."
  - git config --global user.email "my-programming@mail.ru"
  - git config --global user.name "simplespacej"
  - git clone --depth=1 https://$(GITHUB_TOKEN)@github.com/simplespacej/whack-a-mole.git gh-pages || echo "No gh-pages found, creating one"
  - cd gh-pages
  - git checkout gh-pages || git checkout -b gh-pages
  - rsync -av --delete ../dist/ .
  - git add .
  - git commit -m "Update GitHub Pages [ci skip]" || echo "No changes to commit"
  - git push origin gh-pages --force
